name: cvlab2
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - scikit-image
  - scipy
  - matplotlib
  - python=3.9
  - jupyter
  - ipympl
  - pip
  - pytorch
  - torchvision
  - av
  - glob
  - pip:
    - opencv-python
    - imutils
